name: Update Passwords

on:
  schedule:
    - cron: "*/5 * * * *"  # Chạy mỗi 5 phút
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate new passwords
        run: |
          echo '{ "android": "'$(openssl rand -base64 6)'", "ios": "'$(openssl rand -base64 6)'" }' > password.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add password.json
          git commit -m "Update passwords automatically"
          git push
          
